spring:
  profiles:
    active: local
  session:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${NAME}
    username: ${USER_RW}
    password: ${PWD_RW}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  error:
    include-message: always
